basePath: /
definitions:
  mahasiswa.DataMahasiswa:
    properties:
      alamat:
        type: string
      asalsekolah:
        type: string
      namalengkap:
        type: string
      prodi:
        type: string
      userid:
        type: string
    type: object
host: pbo-tugasbesar-c553f4142173.herokuapp.com
info:
  contact:
    email: indra@ulbi.ac.id
    name: API Support
    url: https://github.com/indrariksa
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /api/mahasiswa:
    get:
      consumes:
      - application/json
      description: Mengambil semua data mahasiswa
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mahasiswa.DataMahasiswa'
      summary: Get All Data.
      tags:
      - Mahasiswa
    post:
      consumes:
      - application/json
      description: Input data.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mahasiswa.DataMahasiswa'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mahasiswa.DataMahasiswa'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data.
      tags:
      - Mahasiswa
  /api/mahasiswa/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data.
      parameters:
      - description: Masukan Nama
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mahasiswa.DataMahasiswa'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data.
      tags:
      - Mahasiswa
    put:
      consumes:
      - application/json
      description: Ubah data presensi.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mahasiswa.DataMahasiswa'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mahasiswa.DataMahasiswa'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data presensi.
      tags:
      - Mahasiswa
schemes:
- https
- http
swagger: "2.0"
